### ISSUE TITLE
很多功能不可用 /dashboard/IndexData 500 Internal Server Error

### ISSUE THREAD

**Issue by hktalent** [luxiaok/SaltAdmin#11]
#10
```
 [30/May/2019 15:28:22] "HTTP/1.1 GET /dashboard" - 200 OK
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 239, in process
    return self.handle()
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 462, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 438, in handle_class
    return tocall(*args)
  File "/usr/local/saltadmin/view/main.py", line 27, in inner
    return func(*args)
  File "/usr/local/saltadmin/view/adminCenter.py", line 195, in GET
    rt_data.update(self.salt_minions())
  File "/usr/local/saltadmin/view/adminCenter.py", line 187, in salt_minions
    rt = local.cmd('*','test.ping',timeout=1)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 703, in cmd
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 341, in run_job
    'The salt master could not be contacted. Is master running?'
SaltClientError: The salt master could not be contacted. Is master running?

172.17.0.1:57908 - - [30/May/2019 15:28:22] "HTTP/1.1 GET /dashboard/IndexData" - 500 Internal Server Error
```
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/18223385/58644052-0d3a3500-8333-11e9-8270-f5858ebb7ab8.png">

**Comment by hktalent** [comment]
```
** COLLECTED WARNINGS **
Failed to open memory buffer (/dev/mem): No such file or directory
No SMBIOS nor DMI entry point found, sorry.
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
Permission denied to memory file/device (/dev/mem)
** END OF WARNINGS **
```
