### ISSUE TITLE
参数值不匹配

### ISSUE THREAD

**Issue by liucyao** [luxiaok/SaltAdmin#2]
运行127.0.0.0.1:8080　页面报错：
<type 'exceptions.TypeError'> at /
genSession() takes exactly 9 arguments (8 given)

view/index.py 147行　传入８个参数
genSession(uid,Username,ShowName,LastIP,LastDate,token,Lstat,kpl='yes')

genSession方法定义了9个参数
def genSession(SID,Username,ShowName,LastIP,LastLocation,LastDate,Token,Lstat,kpl):

少传入LastLocaltion值

**Comment by vTNT** [comment]
192.168.107.48:62341 - - [10/Jul/2015 12:55:03] "HTTP/1.1 GET /dashboard" - 500 Internal Server Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 239, in process
    return self.handle()
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 396, in handle_class
    return tocall(_args)
  File "/var/www/html/view/main.py", line 27, in inner
    return func(_args)
  File "/var/www/html/view/adminCenter.py", line 146, in GET
    manu = Local.manu()
  File "/var/www/html/view/adminCenter.py", line 59, in manu
    info = dmidecode.system()
AttributeError: 'module' object has no attribute 'system'

登录的时候就报错了 遇过吗

**Comment by luxiaok** [comment]
需要优化。

**Comment by shineforever** [comment]
info = dmidecode.system() 
这个地方怎么优化啊？！我想进系统看下，现在进去就报错~~能否指点下！

**Comment by wxmgcs** [comment]
注释 info = dmidecode.system()
 改成  info = {}

对我们现在开发的项目，很有借鉴意义
